### DISCUSSION TITLE
Show only the calendar icon?

### DISCUSSION THREAD

**Discussion by browser-bug** [wojtekmaj/react-daterange-picker#120] [Q&A]
Is it possible to show only the calendar icon without the explicit date range text? You can hide the icon via props but not viceversa for what I've understood.
Thanks in advance.

**Comment by wojtekmaj** [comment]
I guess you could hide this via CSS:

```css
.react-daterange-picker__inputGroup {
  display: none;
}

.react-daterange-picker__range-divider {
  display: none;
}

```

https://codesandbox.io/s/react-daterange-picker-no-inputs-5py107

But I'd reconsider if React-DateRange-Picker is the way to go in this case, perhaps using React-Calendar directly would be a better choice.
