### ISSUE TITLE
How to disable inputs, but leave the calendar active?

### ISSUE THREAD

**Issue by tahergalal** [wojtekmaj/react-daterange-picker#16]
I would like to disable the inputs so the user can only select from a calendar and not type it

**Comment by wojtekmaj** [comment]
Hmmmm... You could use

```css
.react-daterange-picker__inputGroup__input {
  user-select: none;
}
```
